### ISSUE TITLE
streamwrapper support for Glob

### ISSUE THREAD

**Issue by michielroding** [webmozart/glob#3]
I have a backuptool that uses a directory structure to store files, e.g.:

/my/path/to/backupfiles/year/month/day/filename.ext

I'd like to unittest my code, so I'm looking into e.g. vfsStream to emulate the expected (and unexpected) structure.

I generate a glob pattern somewhere that is used to find files relating to certain servers, backup types (sql/files/etc) etc. 
php's glob() works fine in production but doesn't work well with vfsStream; webmozart\glob looks promising but doesn't work well with streamwrappers such as vfsStream.

I found Path::isAbsolute() to be the culprit; if I simply return true, the code works fine otherwise.

**Comment by webmozart** [comment]
We can't change `isAbsolute()` to return `true` - that would be wrong, as a URI is not an absolute path. We could however change `Glob` to support both absolute paths and URIs, which would solve your problem - right?

**Comment by michielroding** [comment]
Yes it would!

**Comment by webmozart** [comment]
Stream wrapper support is in 2.0-dev now.

**Comment by michielroding** [comment]
Thanks! I'll try it out asap.
