### ISSUE TITLE
Add Glob::combine()

### ISSUE THREAD

**Issue by webmozart** [webmozart/glob#7]
The method `Glob::combine($glob1, $glob2)` should be added that combines two globs/paths into another, stricter glob/path. The method should behave like this:

* If both globs are static (paths), return the path if they are equal and `null` otherwise.
* If one glob is dynamic (wildcards) and the other static (path), return the path if it matches the glob and `null` otherwise.
* If both globs are dynamic, return the combined glob if they match each other and `null` otherwise.

Example for a combined glob:

```php
Glob::combine('/foo/bar/**/*.yml', '/**/messages.yml') => '/foo/bar/**/messages.yml'
```

This is needed for implementing `GlobBinding::findResources()` in https://github.com/puli/issues/issues/114.

**Comment by nicolopignatelli** [comment]
can you better define "if they match each other" for the combined glob case?
is there any specific rule to combine the two globs?

**Comment by webmozart** [comment]
@nicolopignatelli If you are looking for a mathematical definition of the combination rule:

Let G1, G2, G3 be globs where combine(G1, G2) = G3. Let P(G) be the set of all paths matched by a glob G. Then P(G3) = intersect(P(G1), P(G2))

In other words: The combined glob should match **all** paths that are matched by **both** globs passed to `combine()`.

**Comment by webmozart** [comment]
As it turned out in #8, this seems to be quite complicated to implement. An alternative solution is to list files matching one glob first and then compare their paths against the second glob. That solution is maybe even faster than the complicated solution for small sets of paths. Closing.
