### ISSUE TITLE
Extended glob expressions

### ISSUE THREAD

**Issue by sebwebdev** [webmozart/glob#9]
The current implementation could be extended to support the following expressions.
For reference see http://man7.org/linux/man-pages/man7/glob.7.html

* "?" Wildcard: matches any single character, e.g. "fo?" matches "foo", but not "fo" or "fools"
* Character classes: denoted by brackets "[...]", e.g. "[ABCDEFabcdef0123456789]"
* Ranges: denoted by brackets, e.g. "[A-Fa-f0-9]" (equivalent to the above character class)
* Negation for character classes and ranges: denoted by "!", e.g. "[!aeiouAEIOU]" matches any character, except vowels

**Comment by webmozart** [comment]
All of this is supported already :)
